### ISSUE TITLE
missing file "wiki_dict.json"

### ISSUE THREAD

**Issue by zhehengluoK** [LinguisticAnomalies/pls_retrieval#1]
Hi! I read your work CELLS and found it very interesting and insightful. At present, I am trying to reproduce the experiments, but I found the "wiki_dict.json" which is needed to use to retrieve from Wikipedia by definition seems not to be provided.
I wonder if you could generously share the file. Many thanks.

**Comment by yueguo-50** [comment]
Hi there, just upload it to data/wiki_dict.json.zip.

**Comment by zhehengluoK** [comment]
Thanks for the update! However, the json file seems to be a bit problematic so cannot be opened. could you please double-check it?

**Comment by yueguo-50** [comment]
Thanks for letting me know! Upload it to google drive due to the large size: https://drive.google.com/file/d/1c0nz577gaghbP0GlRfRhOy8EyuSdpHZO/view?usp=share_link
